### ISSUE TITLE
The inputs of UNet

### ISSUE THREAD

**Issue by ZhouCX117** [bcmi/ControlCom-Image-Composition#1]
Hi, I am interested in your excellent work. And could you tell me how you unify the inputs of UNet with shape 64*64? The local embedding shape is 256*1024, the global embedding shape is 768, and the indictor shape is 2*2.

**Comment by bo-zhang-cs** [comment]
Thank you for your interest in our work. The inputs of U-Net does not include what you mentioned. I recommend you to read the first paragraph of Section 4.2 in our paper carefully, which describes the detailed composition of U-Net inputs. Thanks again.

**Comment by ZhouCX117** [comment]
![image](https://github.com/bcmi/ControlCom-Image-Composition/assets/79554332/446ffc27-b2ed-4b09-9ed0-eb4ddec475aa)
I read again and find that the local and global embeddings are not included. Then how do you map the indicator map S to $64\times 64$?

**Comment by bo-zhang-cs** [comment]
As mentioned in the last sentence, we get the indicator map by duplicating the indicator vector at each position of the 2D grid.
