### ISSUE TITLE
Jittery images after 3-4 generations

### ISSUE THREAD

**Issue by Amnx404** [bcmi/ControlCom-Image-Composition#5]
Hi team,
We are trying to generate pest-infused plant images. While the 1st and 2nd generations work well. After the third one, we start to get noisy and jittery images.
![image_480](https://github.com/bcmi/ControlCom-Image-Composition/assets/91665648/40d9fa69-35e7-4d8f-bc23-b3a75157d208)
The actual background looked something similar to this, to the same, but similar.
![203457](https://github.com/bcmi/ControlCom-Image-Composition/assets/91665648/3c88a643-b101-4714-802f-06d0091b6ef4)
Is there a solution/ insight that you can provide for the aforementioned problem?

**Comment by bo-zhang-cs** [comment]
Based on the information from your post, it's hard to identify your issue. I suggest checking the background image and bounding box mask that you inputted.

**Comment by Amnx404** [comment]
Each image grid here represents the background foreground and mask and then 2 generations in sequence. We utilised the generated image as the background image for the next generation that we have in queue. The following generation represents the 0th, 6th and 8th iteration of blending different pests onto the modified background. While the generation quality is not something I am concerned about, what I don't understand is the jittery nature of the generated image. This starts to happen generally after the 3rd image that we blend iteratively.

![0_0](https://github.com/bcmi/ControlCom-Image-Composition/assets/91665648/958c07f2-1cf5-4cb1-8422-23b86208df2d)
![0_6](https://github.com/bcmi/ControlCom-Image-Composition/assets/91665648/0db57c3f-a8ef-4402-aead-95ffa504947b)
![0_8](https://github.com/bcmi/ControlCom-Image-Composition/assets/91665648/a4146a8e-9be3-46f9-807a-ac441cd599f5)

**Comment by bo-zhang-cs** [comment]
I see. Since the background reconstruction of the diffusion model tends to have errors and can degrade details from the original real images, repeatedly using generated images as backgrounds may indeed result in a deterioration of image quality. If you're interested in achieving multi-subject composition, I suggest referring to related work at: https://github.com/ali-vilab/AnyDoor.

**Comment by bo-zhang-cs** [comment]
> I see. Since the background reconstruction of the diffusion model tends to have errors and can degrade details from the original real images, repeatedly using generated images as backgrounds may indeed result in a deterioration of image quality. If you're interested in achieving multi-subject composition, I suggest referring to related work at: https://github.com/ali-vilab/AnyDoor.

Another alternative method is to replace the background region of each generated image with a real background, and then feed into the model again.

**Comment by Amnx404** [comment]
Thank you for taking the time to provide your suggestions. I appreciate your insights and will definitely check them out. If you have any further suggestions, please let me know. Just to provide some context, we are currently working on training object detection models using large-scale synthetic image datasets. Our focus is on plant backgrounds and pest-based foregrounds.
