### ISSUE TITLE
运行finetune_mvimgnet时候报缺少module：ldm.data.__pycache__.pcache_access

### ISSUE THREAD

**Issue by zhongjiewei** [bcmi/ControlCom-Image-Composition#6]
![2024-05-07_17h03_15](https://github.com/bcmi/ControlCom-Image-Composition/assets/24388163/f697de41-2f7b-4513-b7d9-82a216de4c9c)
好像train代码中没有这个模块

**Comment by bo-zhang-cs** [comment]
pcache是在公司训练时需要用到的库，本地训练不需要，因此已经删除了。建议把dataset相关的代码都改成从本地读取。
