### ISSUE TITLE
Bad results, any idea why?

### ISSUE THREAD

**Issue by aviadmx** [bcmi/ControlCom-Image-Composition#9]
Blending and harmony generates new content in the background:
![ControlCom_blend_harm](https://github.com/user-attachments/assets/9bfd3590-a7d1-4799-832b-54dc489b1fe4)

Original aspect ratio is not preserved here, the cream is originally a narrow portrait image:
![ControlCom_blend_harm](https://github.com/user-attachments/assets/74c54de8-b0dc-4d7e-b2c7-ae7ff402e5ca)

Blending and harmony again generates noise in the background:
![ControlCom_blend_harm](https://github.com/user-attachments/assets/23d71942-5dff-43f2-9938-d800dca742b9)

Here is with view & composition alternation:
![ControlCom_general_model_view_comp](https://github.com/user-attachments/assets/4ebf3222-fbdb-405d-ba1b-ae452113868b)

Been using the `tests/test_controllable_composition.py` script with my own images, nothing else is altered. Any idea how to improve results, or are these out of domain for the model?

**Comment by ustcnewly** [comment]
(1) This model does not have the ability to preserve the background within the bounding box. It will re-generate the background pixels within the bounding box. Sometimes the re-generated background is undesirable.
(2)  The foreground will fill up the bounding box by default, so its aspect ratio is determined by the bounding box. You can first remove the original object using image inpainting and then redraw the bounding box.
(3) The  same reason as (1). In this case, the model needs to re-generate the hand, which makes the results worse. 
(4) The shoe is rotated a little bit.
